index-region:
    path: /
    controller: App\Controller\IndexController::indexAction

index-state:
    path: /{region}/estados
    controller: App\Controller\IndexController::stateAction

index-city:
    path: /cidades/{uf}
    controller: App\Controller\IndexController::cityAction
